config/routes.rb
Rails.application.routes.draw do
  root to: 'records#new'
  get 'records/new', to: 'records#new'
  post 'records', to: 'records#create'
  get 'records', to: 'records#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/record.rb
class Record < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  def new
    @record = Record.new
  end

  def create
    @record = Record.create(record_params)
    if @record.save
      redirect_to   records_new_path
    else
      render :new
    end
  end

  def index
    @records = Record.all
  end

  private

  def record_params
    params.require(:record).permit(:Url, :summary)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Func</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/records/index.html.erb
<%= link_to 'Post form', records_new_path, method: :get %>
<div class="card">
  <% @records.each do |r| %>
    <div class="card_body">
      <div class="card_Url">
        <%= raw Rinku.auto_link(r.Url, :all, 'target="_blank"') %>
      </div>
      <div class="card_summary">
        <%= r.summary %>
      </div>
    </div>
  <% end %>
</div>

app/views/records/new.html.erb
<div class="contents">
  <%= link_to 'Data list', records_path, method: :get %>
  <%= form_with model: @record do |f| %>
    <div class="field">
      <%= f.text_area :Url, placeholder: "URL" %>
    </div>
    <div class="field">
      <%= f.text_area :summary, placeholder: "概要", rows: "30" %>
    </div>
    <div class="field">
      <%= f.submit %>
    </div>
  <% end %>
</div>